/*
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LxcoreRuntimeModule extends AbstractLxcoreRuntimeModule {
}
