/*
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LxcoreStandaloneSetup extends LxcoreStandaloneSetupGenerated {

	def static void doSetup() {
		new LxcoreStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
