/**
 *
 * $Id$
 */
package lcore.validation;

import lcore.XPackage;
import lcore.XTypeParameter;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * A sample validator interface for {@link lcore.XClassifier}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XClassifierValidator {
	boolean validate();

	boolean validateInstanceType(JvmTypeReference value);
	boolean validatePackage(XPackage value);
	boolean validateTypeParameters(EList<XTypeParameter> value);
}
