/**
 *
 * $Id$
 */
package lcore.validation;

import lcore.XGenericType;
import lcore.XMember;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lcore.XClass}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XClassValidator {
	boolean validate();

	boolean validateAbstract(boolean value);
	boolean validateInterface(boolean value);
	boolean validateMembers(EList<XMember> value);
	boolean validateSuperTypes(EList<XGenericType> value);
}
