/**
 *
 * $Id$
 */
package lcore.validation;

import lcore.XGenericType;
import lcore.XParameter;
import lcore.XTypeParameter;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.xbase.XBlockExpression;

/**
 * A sample validator interface for {@link lcore.XOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XOperationValidator {
	boolean validate();

	boolean validateTypeParameters(EList<XTypeParameter> value);
	boolean validateParameters(EList<XParameter> value);
	boolean validateExceptions(EList<XGenericType> value);
	boolean validateBody(XBlockExpression value);
}
