/**
 *
 * $Id$
 */
package lcore.validation;

import lcore.XClassifier;
import lcore.XImportDirective;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link lcore.XPackage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XPackageValidator {
	boolean validate();

	boolean validateImportDirectives(EList<XImportDirective> value);
	boolean validateClassifiers(EList<XClassifier> value);
}
