/**
 *
 * $Id$
 */
package lcore.validation;

import lcore.XOperation;

/**
 * A sample validator interface for {@link lcore.XParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XParameterValidator {
	boolean validate();

	boolean validateOperation(XOperation value);
}
