/**
 *
 * $Id$
 */
package lcore.validation;

import org.eclipse.xtext.xbase.XBlockExpression;

/**
 * A sample validator interface for {@link lcore.XStructuralFeature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XStructuralFeatureValidator {
	boolean validate();

	boolean validateReadonly(boolean value);
	boolean validateVolatile(boolean value);
	boolean validateTransient(boolean value);
	boolean validateUnsettable(boolean value);
	boolean validateDerived(boolean value);
	boolean validateGetBody(XBlockExpression value);
	boolean validateSetBody(XBlockExpression value);
	boolean validateIsSetBody(XBlockExpression value);
	boolean validateUnsetBody(XBlockExpression value);
}
