/*
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.xcore.lang.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractLxcoreScopeProvider extends XbaseBatchScopeProvider {
}
