/*
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore.lang.ui.tests;

import com.google.inject.Injector;
import fr.inria.diverse.xcore.lang.ui.internal.LangActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LxcoreUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("fr.inria.diverse.xcore.lang.Lxcore");
	}

}
