/*
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.xcore.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LxcoreAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/inria/diverse/xcore/lang/parser/antlr/internal/InternalLxcore.tokens");
	}
}
