/*
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore.lang.ui;

import com.google.inject.Injector;
import fr.inria.diverse.xcore.lang.ui.internal.LangActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LxcoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LangActivator.getInstance().getInjector(LangActivator.FR_INRIA_DIVERSE_XCORE_LANG_LXCORE);
	}
	
}
