/**
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore_light.lcore;

import org.eclipse.emf.common.util.EList;

import org.eclipse.xtext.common.types.JvmTypeReference;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XClassifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.xcore_light.lcore.XClassifier#getInstanceType <em>Instance Type</em>}</li>
 *   <li>{@link fr.inria.diverse.xcore_light.lcore.XClassifier#getPackage <em>Package</em>}</li>
 *   <li>{@link fr.inria.diverse.xcore_light.lcore.XClassifier#getTypeParameters <em>Type Parameters</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXClassifier()
 * @model abstract="true"
 * @generated
 */
public interface XClassifier extends XNamedElement {
	/**
	 * Returns the value of the '<em><b>Instance Type</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Instance Type</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Instance Type</em>' containment reference.
	 * @see #setInstanceType(JvmTypeReference)
	 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXClassifier_InstanceType()
	 * @model containment="true"
	 * @generated
	 */
	JvmTypeReference getInstanceType();

	/**
	 * Sets the value of the '{@link fr.inria.diverse.xcore_light.lcore.XClassifier#getInstanceType <em>Instance Type</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Instance Type</em>' containment reference.
	 * @see #getInstanceType()
	 * @generated
	 */
	void setInstanceType(JvmTypeReference value);

	/**
	 * Returns the value of the '<em><b>Package</b></em>' container reference.
	 * It is bidirectional and its opposite is '{@link fr.inria.diverse.xcore_light.lcore.XPackage#getClassifiers <em>Classifiers</em>}'.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Package</em>' container reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Package</em>' container reference.
	 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXClassifier_Package()
	 * @see fr.inria.diverse.xcore_light.lcore.XPackage#getClassifiers
	 * @model opposite="classifiers" changeable="false"
	 * @generated
	 */
	XPackage getPackage();

	/**
	 * Returns the value of the '<em><b>Type Parameters</b></em>' containment reference list.
	 * The list contents are of type {@link fr.inria.diverse.xcore_light.lcore.XTypeParameter}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Type Parameters</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Type Parameters</em>' containment reference list.
	 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXClassifier_TypeParameters()
	 * @model containment="true"
	 * @generated
	 */
	EList<XTypeParameter> getTypeParameters();

} // XClassifier
