/**
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore_light.lcore;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XGeneric Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.xcore_light.lcore.XGenericType#getUpperBound <em>Upper Bound</em>}</li>
 *   <li>{@link fr.inria.diverse.xcore_light.lcore.XGenericType#getTypeArguments <em>Type Arguments</em>}</li>
 *   <li>{@link fr.inria.diverse.xcore_light.lcore.XGenericType#getLowerBound <em>Lower Bound</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXGenericType()
 * @model
 * @generated
 */
public interface XGenericType extends EObject {
	/**
	 * Returns the value of the '<em><b>Upper Bound</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Upper Bound</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Upper Bound</em>' containment reference.
	 * @see #setUpperBound(XGenericType)
	 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXGenericType_UpperBound()
	 * @model containment="true"
	 * @generated
	 */
	XGenericType getUpperBound();

	/**
	 * Sets the value of the '{@link fr.inria.diverse.xcore_light.lcore.XGenericType#getUpperBound <em>Upper Bound</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Upper Bound</em>' containment reference.
	 * @see #getUpperBound()
	 * @generated
	 */
	void setUpperBound(XGenericType value);

	/**
	 * Returns the value of the '<em><b>Type Arguments</b></em>' containment reference list.
	 * The list contents are of type {@link fr.inria.diverse.xcore_light.lcore.XGenericType}.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Type Arguments</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Type Arguments</em>' containment reference list.
	 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXGenericType_TypeArguments()
	 * @model containment="true"
	 * @generated
	 */
	EList<XGenericType> getTypeArguments();

	/**
	 * Returns the value of the '<em><b>Lower Bound</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Lower Bound</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Lower Bound</em>' containment reference.
	 * @see #setLowerBound(XGenericType)
	 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXGenericType_LowerBound()
	 * @model containment="true"
	 * @generated
	 */
	XGenericType getLowerBound();

	/**
	 * Sets the value of the '{@link fr.inria.diverse.xcore_light.lcore.XGenericType#getLowerBound <em>Lower Bound</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Lower Bound</em>' containment reference.
	 * @see #getLowerBound()
	 * @generated
	 */
	void setLowerBound(XGenericType value);

} // XGenericType
