/**
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore_light.lcore;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XModel Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXModelElement()
 * @model abstract="true"
 * @generated
 */
public interface XModelElement extends EObject {
} // XModelElement
