/**
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore_light.lcore;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XPackage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.inria.diverse.xcore_light.lcore.XPackage#getImportDirectives <em>Import Directives</em>}</li>
 *   <li>{@link fr.inria.diverse.xcore_light.lcore.XPackage#getClassifiers <em>Classifiers</em>}</li>
 * </ul>
 *
 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXPackage()
 * @model
 * @generated
 */
public interface XPackage extends XNamedElement {
	/**
	 * Returns the value of the '<em><b>Import Directives</b></em>' containment reference list.
	 * The list contents are of type {@link fr.inria.diverse.xcore_light.lcore.XImportDirective}.
	 * It is bidirectional and its opposite is '{@link fr.inria.diverse.xcore_light.lcore.XImportDirective#getPackage <em>Package</em>}'.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Import Directives</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Import Directives</em>' containment reference list.
	 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXPackage_ImportDirectives()
	 * @see fr.inria.diverse.xcore_light.lcore.XImportDirective#getPackage
	 * @model opposite="package" containment="true"
	 * @generated
	 */
	EList<XImportDirective> getImportDirectives();

	/**
	 * Returns the value of the '<em><b>Classifiers</b></em>' containment reference list.
	 * The list contents are of type {@link fr.inria.diverse.xcore_light.lcore.XClassifier}.
	 * It is bidirectional and its opposite is '{@link fr.inria.diverse.xcore_light.lcore.XClassifier#getPackage <em>Package</em>}'.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Classifiers</em>' containment reference list isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Classifiers</em>' containment reference list.
	 * @see fr.inria.diverse.xcore_light.lcore.LcorePackage#getXPackage_Classifiers()
	 * @see fr.inria.diverse.xcore_light.lcore.XClassifier#getPackage
	 * @model opposite="package" containment="true"
	 * @generated
	 */
	EList<XClassifier> getClassifiers();

} // XPackage
