/*
 * generated by Xtext 2.14.0
 */
package fr.inria.diverse.xcore.lang.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class LxcoreEditor extends XbaseEditor {
}
