/*
 * generated by Xtext 2.12.0
 */
package fr.inria.diverse.xcore.lang.tests

import com.google.inject.Inject
import fr.inria.diverse.xcore_light.lcore.XPackage
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(LxcoreInjectorProvider)
class LxcoreParsingTest {
	@Inject
	ParseHelper<XPackage> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
